name: presentation
description: Presentation module
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: "3.27.1"

dependencies:
  bloc_concurrency: 0.2.5
  cached_network_image: 3.4.1
  collection: 1.19.0
  domain:
    path: ../domain
  easy_debounce: 2.0.3
  envied: 1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_hooks: 0.20.5
  flutter_localizations:
    sdk: flutter
  fpdart: 1.1.1
  freezed_annotation: 2.4.4
  get_it: 8.0.3
  go_router: 14.6.2
  google_fonts: 6.2.1
  infinite_scroll_pagination: 4.1.0
  intl: 0.19.0
  remote:
    path: ../remote

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: 2.4.14
  envied_generator: 1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  freezed: 2.5.7
  mockingjay: 0.6.0
  mocktail: 1.0.4
