name: remote
description: Remote module
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: "3.27.1"

dependencies:
  collection: 1.19.0
  dio: 5.7.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_pretty_dio_logger: 3.0.0
  fpdart: 1.1.1
  freezed_annotation: 2.4.4
  get_it: 8.0.3
  json_annotation: 4.9.0
  json_serializable: 6.8.0
  retrofit: 4.4.1

dev_dependencies:
  build_runner: 2.4.14
  flutter_lints: 5.0.0
  freezed: 2.5.7
  mocktail: 1.0.4
  platform: 3.1.6
  retrofit_generator: 9.1.5
  test: 1.25.13
